TodoListApp/urls.py
"""TodoListApp URL Configuration
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('api/', include('api.urls'))
]

api/urls.py
from django.urls import path
from .import views

app_name = 'api'

urlpatterns = [
	path('retrieve-and-create-todos', views.TodoApiView.as_view(), name="todos-cr"),
	path('edit-todo/<int:todo_id>', views.EditTodoView.as_view(), name="todo-u"),
	path('delete-todo/<int:todo_id>', views.DeleteTodoView.as_view(), name="todo-del")
]

todo/urls.py
from django.urls import path 
from .import views
app_name = 'todo'

urlpatterns = [
	path('', views.index, name='index'),
	path('update', views.updateTodo, name="update"),
	path('create', views.createTodo, name='create'),
	path('delete', views.deleteTodo, name='delete')
]

api/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
	body 			= models.CharField(max_length=50)
	done 			= models.BooleanField(default=False)
	date_created	= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.body

todo/models.py
from django.db import models

# Create your models here.
class TodoModel(models.Model):
	todo_body 			= models.CharField(max_length=50)
	finished 			= models.BooleanField(default=False)
	date_created 		= models.DateTimeField(auto_now_add=True)
	date_updated 		= models.DateTimeField(auto_now=True)

	class Meta:
		ordering =['-id']
	

	

api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import *
from .models import Todo
# Create your views here.


class TodoApiView(APIView):
	serializer_class = TodoSerializer

	def get(self, request):
		try:
			todos 			= Todo.objects.all()
			data 			= TodoSerializer(todos, many=True)
			return Response({
				"status":status.HTTP_200_OK,
				"data": data.data
				}, status.HTTP_200_OK)

		except:
			return Response({
				"status":status.HTTP_500_INTERNAL_SERVER_ERROR,
				"message": "Something went wrong"
				}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

	def post(self, request):
		try:
			data = TodoSerializer(data=request.data)
			data.is_valid(raise_exception=False)
			request_data = data.data

			todo 		= Todo.objects.create(body=request_data["body"])

			return Response({
				"status":status.HTTP_201_CREATED,
				"message": "Todo added successfully"
				},status=status.HTTP_201_CREATED)

		except Exception as e:
			return Response({
				"status":status.HTTP_400_BAD_REQUEST,
				"message": str(e)
				},status=status.HTTP_400_BAD_REQUEST)

	
	

class EditTodoView(APIView):
	serializer_class = EditSerializer

	def put(self, request, todo_id):
		try:
			data = EditSerializer(data=request.data)
			data.is_valid(raise_exception=False)
			request_data = data.data

			getTodo 	= Todo.objects.get(id=todo_id)
			if request_data["done"]==True:
				getTodo.done = True
			else:
				getTodo.done= False 
				 
			if request_data["body"]:
				getTodo.body = request_data["body"]
			getTodo.save()
			return Response({
				"status": status.HTTP_200_OK,
				"message":"Todo modification successful"
				}, status=status.HTTP_200_OK)

		except Todo.DoesNotExist:
			return Response({
				"status":status.HTTP_404_NOT_FOUND,
				"message":"Todo not found"
				}, status=status.HTTP_404_NOT_FOUND)
		except Exception as e:
			return Response({
				"status":status.HTTP_500_INTERNAL_SERVER_ERROR,
				"message":str(e)
				}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class DeleteTodoView(APIView):
	def delete(self, request, todo_id):
		try:
			getTodo 	= Todo.objects.get(id=todo_id)
			getTodo.delete()
			return Response({
				"status":status.HTTP_200_OK,
				"message":"Todo removed successfully"
				}, status=status.HTTP_200_OK) 
		except Todo.DoesNotExist:
			return Response({
				"status":status.HTTP_404_NOT_FOUND,
				"message":"Todo not found"
				}, status=status.HTTP_404_NOT_FOUND)
		except Exception as e:
			return Response({
				"status":status.HTTP_500_INTERNAL_SERVER_ERROR,
				"message":str(e)
				}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import TodoModel
from api.models import Todo
# Create your views here.

# Retrieve
def index(request):
	todos 		= Todo.objects.all()
	
	context = {
		"todos":todos
	}
	return render(request, 'index.html',context)

# Create
def createTodo(request):
	if request.method =="POST":
		body 		= request.POST.get("body")
		new_todo  	= Todo.objects.create(body=body)
		new_todo.save()
		return redirect("todo:index")

# Update
def updateTodo(request):
	if request.method =='POST':
		body 		= request.POST.get('todo_id')
		update_todo	= Todo.objects.get(id=body)
		update_todo.done = True
		update_todo.save()
		return redirect('todo:index')

# Delete
def deleteTodo(request):
	if request.method =='POST':
		body 		= request.POST.get('todo_id')
		delete_todo = Todo.objects.get(id=body)
		delete_todo.delete()
		return redirect('todo:index')


	

todo/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>TodoListApp</title>
  <meta name="description" content="Todo List App. For staying more organinsed and disciplined">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<style type="text/css">
  .action-btns{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }
  
</style>
</head>
<body>
	<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">TODO LIST APP</h4>

            <form method="POST" action="{% url 'todo:create' %}" class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              {% csrf_token %}
              <div class="action-btns">
                <div class="col-9 px-3" class="todo-input">
                  <div class="form-outline">
                    <input type="text" id="form1" name="body" class="form-control" required/>
                    <label class="form-label" for="form1">Enter a task here</label>
                  </div>
                </div>

                <div class="col-3">
                  <button type="submit" class="btn btn-primary">Add</button>
                </div>
              </div>
              
            </form>

            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">Todo item</th>
                  <th scope="col">Status</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for todo in todos %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  {% if todo.done %}
                    <td style="text-decoration: line-through;">{{todo.body}}</td>
                  {% else %}
                    <td>{{todo.body}}</td>
                  {% endif %}
                  <td>
                      {% if todo.done %}
                          Finished
                      {% else %}
                          In progress
                      {% endif %}
                    </td>
                  <td>
                    <div class="action-btns">
                      <form method="POST" action="{% url 'todo:delete' %}">
                        {% csrf_token %}
                          <input type="text" name="todo_id" value="{{todo.id}}" style="display: none;">
                          <button type="submit" class="btn btn-danger">Delete</button>
                      </form>

                      {% if todo.done %}
                      {% else %}
                      <form method="POST" action="{% url 'todo:update' %}">
                            {% csrf_token %}
                          <input type="text" name="todo_id" value="{{todo.id}}" style="display: none;">
                          <button type="submit" class="btn btn-success ms-1">Finished</button>
                      </form>
                      {% endif %}
                    </div>

                  </td>
                </tr>
                {% empty %}
                <tr>
                <td>
                  <center>
                      <h2>Todo list is empty</h2>
                  </center>
                </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>
</html>